//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_r_layeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konta
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
        public string Mail { get; set; }
        public Nullable<int> Nr_telefonu { get; set; }
        public string Rodzaj_konta { get; set; }
    }
}
